import { AuthConstants } from '@/types';
import { appConstants } from './app.constant';

const authentication: string = 'authentication';

export const authConstants: AuthConstants = {
  LOGIN: 'LOGIN',
  LOGGING_IN: 'LOGGING_IN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',
  LOGGING_OUT: 'LOGGING_OUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  VERIFY_EMAIL: 'VERIFY_EMAIL',
  REQUEST_VERIFY_EMAIL: 'REQUEST_VERIFY_EMAIL',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_ERROR: 'VERIFY_EMAIL_ERROR',

  RESEND_EMAIL_LINK: 'RESEND_EMAIL_LINK',
  REQUEST_RESEND_EMAIL_LINK: 'REQUEST_RESEND_EMAIL_LINK',
  RESEND_EMAIL_LINK_SUCCESS: 'RESEND_EMAIL_LINK_SUCCESS',
  RESEND_EMAIL_LINK_ERROR: 'RESEND_EMAIL_LINK_ERROR',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  REQUEST_CHANGE_PASSWORD: 'REQUEST_CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  TOKEN_HAS_EXPIRED: 'TOKEN_HAS_EXPIRED',
  USER_KEY: 'USER_KEY',
  USER_ROLE_ID: 2,

  LOGIN_URI: `${appConstants.BASE_URI}${authentication}/login`,
  AUTH_URI: `${appConstants.BASE_URI}${authentication}`,
};
