import { appConstants } from './app.constant';

const category = 'category';

export const categoryConstants = {
  REQUEST_GET_CATEGORIES: 'REQUEST_GET_CATEGORIES',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_ERROR: 'GET_CATEGORIES_ERROR',
  GET_CATEGORIES: 'GET_CATEGORIES',

  REQUEST_CREATE_CATEGORY: 'REQUEST_CREATE_CATEGORY',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',
  CREATE_CATEGORY: 'CREATE_CATEGORY',

  REQUEST_UPDATE_CATEGORY: 'REQUEST_UPDATE_CATEGORY',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_ERROR: 'UPDATE_CATEGORY_ERROR',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',

  REQUEST_DELETE_CATEGORY: 'REQUEST_DELETE_CATEGORY',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_ERROR: 'DELETE_CATEGORY_ERROR',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  REQUEST_SET_CATEGORY_STATUS: 'REQUEST_SET_CATEGORY_STATUS',
  SET_CATEGORY_STATUS_SUCCESS: 'SET_CATEGORY_STATUS_SUCCESS',
  SET_CATEGORY_STATUS_ERROR: 'SET_CATEGORY_STATUS_ERROR',
  ACTIVATE_CATEGORY: 'ACTIVATE_CATEGORY',
  DEACTIVATE_CATEGORY: 'DEACTIVATE_CATEGORY',

  CATEGORY_URI: `${appConstants.BASE_URI}${category}`,
};
