import { appConstants } from './app.constant';

export const configConstants = {
  GET_EFFECTIVE_CONFIG: 'GET_EFFECTIVE_CONFIG',
  REQUEST_GET_EFFECTIVE_CONFIG: 'REQUEST_GET_EFFECTIVE_CONFIG',
  GET_EFFECTIVE_CONFIG_SUCCESS: 'GET_EFFECTIVE_CONFIG_SUCCESS',
  GET_EFFECTIVE_CONFIG_FAILURE: 'GET_EFFECTIVE_CONFIG_FAILURE',

  GET_SETTINGS: 'GET_SETTINGS',
  REQUEST_GET_SETTINGS: 'REQUEST_GET_SETTINGS',
  GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
  GET_SETTINGS_FAILURE: 'GET_SETTINGS_FAILURE',

  UPDATE_SETTING: 'UPDATE_SETTING',
  REQUEST_UPDATE_SETTING: 'REQUEST_UPDATE_SETTING',
  UPDATE_SETTING_SUCCESS: 'UPDATE_SETTING_SUCCESS',
  UPDATE_SETTING_FAILURE: 'UPDATE_SETTING_FAILURE',

  RESET_SETTING: 'RESET_SETTING',

  CONFIG_URI: `${appConstants.BASE_URI}configuration`,
};
