export const cronConstants = {
  GET_CRONS: 'GET_CRONS',
  REQUEST_GET_CRONS: 'REQUEST_GET_CRONS',
  GET_CRONS_SUCCESS: 'GET_CRONS_SUCCESS',
  GET_CRONS_FAILURE: 'GET_CRONS_FAILURE',

  UPDATE_CRON: 'UPDATE_CRON',
  REQUEST_UPDATE_CRON: 'REQUEST_UPDATE_CRON',
  UPDATE_CRON_SUCCESS: 'UPDATE_CRON_SUCCESS',
  UPDATE_CRON_FAILURE: 'UPDATE_CRON_FAILURE',

  TRIGGER_CRON: 'TRIGGER_CRON',
  REQUEST_TRIGGER_CRON: 'REQUEST_TRIGGER_CRON',
  TRIGGER_CRON_SUCCESS: 'TRIGGER_CRON_SUCCESS',
  TRIGGER_CRON_FAILURE: 'TRIGGER_CRON_FAILURE',

  VALIDATE_CRON: 'VALIDATE_CRON',
  REQUEST_VALIDATE_CRON: 'REQUEST_VALIDATE_CRON',
  VALIDATE_CRON_SUCCESS: 'VALIDATE_CRON_SUCCESS',
  VALIDATE_CRON_FAILURE: 'VALIDATE_CRON_FAILURE',

  CRON_URI: 'system-cron',
};
