import { appConstants } from './app.constant';

export const dashboardConstants = {
  GET_DASHBOARD_STATS: 'GET_DASHBOARD_STATS',
  REQUEST_GET_DASHBOARD_STATS: 'REQUEST_GET_DASHBOARD_STATS',
  GET_DASHBOARD_STATS_SUCCESS: 'GET_DASHBOARD_STATS_SUCCESS',
  GET_DASHBOARD_STATS_ERROR: 'GET_DASHBOARD_STATS_ERROR',

  GET_DASHBOARD_ANALYTICS: 'GET_DASHBOARD_ANALYTICS',
  REQUEST_GET_DASHBOARD_ANALYTICS: 'REQUEST_GET_DASHBOARD_ANALYTICS',
  GET_DASHBOARD_ANALYTICS_SUCCESS: 'GET_DASHBOARD_ANALYTICS_SUCCESS',
  GET_DASHBOARD_ANALYTICS_ERROR: 'GET_DASHBOARD_ANALYTICS_ERROR',

  DASHBOARD_URI: `${appConstants.BASE_URI}dashboard`,
};
