import { appConstants } from './app.constant';

const dashboard: string = 'dashboard';

export const dashboardConstants = {
   REQUEST_GET_DASHBOARD_STATS: 'REQUEST_GET_DASHBOARD_STATS',
   GET_DASHBOARD_STATS_SUCCESS: 'GET_DASHBOARD_STATS_SUCCESS',
   GET_DASHBOARD_STATS_ERROR: 'GET_DASHBOARD_STATS_ERROR',

   REQUEST_GET_DASHBOARD_ANALYTICS: 'REQUEST_GET_DASHBOARD_ANALYTICS',
   GET_DASHBOARD_ANALYTICS_SUCCESS: 'GET_DASHBOARD_ANALYTICS_SUCCESS',
   GET_DASHBOARD_ANALYTICS_ERROR: 'GET_DASHBOARD_ANALYTICS_ERROR',

   GET_DASHBOARD_STATS: 'GET_DASHBOARD_STATS',
   GET_DASHBOARD_ANALYTICS: 'GET_DASHBOARD_ANALYTICS',

   DASHBOARD_URI: `${appConstants.BASE_URI}${dashboard}`,
   DAILY_REPORT_URI: `${appConstants.BASE_URI}${dashboard}/daily-report`,
};
