import { DepartmentConstants } from '@/types';
import { appConstants } from './app.constant';

const department: string = 'department';

export const departmentConstants: DepartmentConstants = {
  REQUEST_GET_ALL_DEPARTMENTS: 'REQUEST_GET_ALL_DEPARTMENTS',
  GET_ALL_DEPARTMENTS_SUCCESS: 'GET_ALL_DEPARTMENTS_SUCCESS',
  GET_ALL_DEPARTMENTS_ERROR: 'GET_ALL_DEPARTMENTS_ERROR',

  REQUEST_CREATE_DEPARTMENT: 'REQUEST_CREATE_DEPARTMENT',
  CREATE_DEPARTMENT_SUCCESS: 'CREATE_DEPARTMENT_SUCCESS',
  CREATE_DEPARTMENT_ERROR: 'CREATE_DEPARTMENT_ERROR',

  GET_ALL_DEPARTMENTS: 'GET_ALL_DEPARTMENTS',
  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',

  DEPARTMENT_URI: `${appConstants.BASE_URI}${department}`,
};
