import { GeneratorConstants } from '@/types';
import { appConstants } from './app.constant';

const generator: string = 'generator-log';

export const generatorConstants: GeneratorConstants = {
  REQUEST_GET_GENERATOR_LOGS: 'REQUEST_GET_GENERATOR_LOGS',
  GET_GENERATOR_LOGS_SUCCESS: 'GET_GENERATOR_LOGS_SUCCESS',
  GET_GENERATOR_LOGS_ERROR: 'GET_GENERATOR_LOGS_ERROR',

  REQUEST_CREATE_GENERATOR_LOG: 'REQUEST_CREATE_GENERATOR_LOG',
  CREATE_GENERATOR_LOG_SUCCESS: 'CREATE_GENERATOR_LOG_SUCCESS',
  CREATE_GENERATOR_LOG_ERROR: 'CREATE_GENERATOR_LOG_ERROR',

  REQUEST_SEARCH_GENERATOR_LOG: 'REQUEST_SEARCH_GENERATOR_LOG',
  SEARCH_GENERATOR_LOG_SUCCESS: 'SEARCH_GENERATOR_LOG_SUCCESS',
  SEARCH_GENERATOR_LOG_ERROR: 'SEARCH_GENERATOR_LOG_ERROR',

  GET_GENERATOR_LOGS: 'GET_GENERATOR_LOGS',
  CREATE_GENERATOR_LOG: 'CREATE_GENERATOR_LOG',
  SEARCH_GENERATOR_LOG: 'SEARCH_GENERATOR_LOG',

  GENERATOR_URI: `${appConstants.BASE_URI}${generator}`,
};
