import { IncidenceLogConstants } from '@/types/incidenceLog';
import { appConstants } from './app.constant';

const incidence = 'incidence-log';

export const incidenceLogConstants: IncidenceLogConstants = {
   REQUEST_GET_INCIDENCE_LOGS: 'REQUEST_GET_INCIDENCE_LOGS',
   GET_INCIDENCE_LOGS_SUCCESS: 'GET_INCIDENCE_LOGS_SUCCESS',
   GET_INCIDENCE_LOGS_ERROR: 'GET_INCIDENCE_LOGS_ERROR',

   REQUEST_CREATE_INCIDENCE_LOG: 'REQUEST_CREATE_INCIDENCE_LOG',
   CREATE_INCIDENCE_LOG_SUCCESS: 'CREATE_INCIDENCE_LOG_SUCCESS',
   CREATE_INCIDENCE_LOG_ERROR: 'CREATE_INCIDENCE_LOG_ERROR',

   REQUEST_UPDATE_INCIDENCE_LOG: 'REQUEST_UPDATE_INCIDENCE_LOG',
   UPDATE_INCIDENCE_LOG_SUCCESS: 'UPDATE_INCIDENCE_LOG_SUCCESS',
   UPDATE_INCIDENCE_LOG_ERROR: 'UPDATE_INCIDENCE_LOG_ERROR',

   REQUEST_DELETE_INCIDENCE_LOG: 'REQUEST_DELETE_INCIDENCE_LOG',
   DELETE_INCIDENCE_LOG_SUCCESS: 'DELETE_INCIDENCE_LOG_SUCCESS',
   DELETE_INCIDENCE_LOG_ERROR: 'DELETE_INCIDENCE_LOG_ERROR',

   GET_INCIDENCE_LOGS: 'GET_INCIDENCE_LOGS',
   CREATE_INCIDENCE_LOG: 'CREATE_INCIDENCE_LOG',
   UPDATE_INCIDENCE_LOG: 'UPDATE_INCIDENCE_LOG',
   DELETE_INCIDENCE_LOG: 'DELETE_INCIDENCE_LOG',

   INCIDENCE_LOG_URI: `${appConstants.BASE_URI}${incidence}`,
};
