import { ItemConstants } from '@/types';
import { appConstants } from './app.constant';

const item: string = 'item';

export const itemConstants: ItemConstants = {
  REQUEST_GET_DEPARTMENT_ITEMS: 'REQUEST_GET_DEPARTMENT_ITEMS',
  GET_DEPARTMENT_ITEMS_SUCCESS: 'GET_DEPARTMENT_ITEMS_SUCCESS',
  GET_DEPARTMENT_ITEMS_ERROR: 'GET_DEPARTMENT_ITEMS_ERROR',

  REQUEST_GET_ALL_DEPARTMENT_ITEMS: 'REQUEST_GET_ALL_DEPARTMENT_ITEMS',
  GET_ALL_DEPARTMENT_ITEMS_SUCCESS: 'GET_ALL_DEPARTMENT_ITEMS_SUCCESS',
  GET_ALL_DEPARTMENT_ITEMS_ERROR: 'GET_ALL_DEPARTMENT_ITEMS_ERROR',

  REQUEST_GET_ALL_ITEMS: 'REQUEST_GET_ALL_ITEMS',
  GET_ALL_ITEMS_SUCCESS: 'GET_ALL_ITEMS_SUCCESS',
  GET_ALL_ITEMS_ERROR: 'GET_ALL_ITEMS_ERROR',

  REQUEST_CREATE_ITEM: 'REQUEST_CREATE_ITEM',
  CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
  CREATE_ITEM_ERROR: 'CREATE_ITEM_ERROR',

  REQUEST_SEARCH_ITEM: 'REQUEST_SEARCH_ITEM',
  SEARCH_ITEM_SUCCESS: 'SEARCH_ITEM_SUCCESS',
  SEARCH_ITEM_ERROR: 'SEARCH_ITEM_ERROR',

  GET_DEPARTMENT_ITEMS: 'GET_DEPARTMENT_ITEMS',
  GET_ALL_DEPARTMENT_ITEMS: 'GET_ALL_DEPARTMENT_ITEMS',
  GET_ALL_ITEMS: 'GET_ALL_ITEMS',

  CREATE_ITEM: 'CREATE_ITEM',
  SEARCH_ITEM: 'SEARCH_ITEM',

  ITEM_URI: `${appConstants.BASE_URI}${item}`,
};
