import { ItemConstants } from '@/types';
import { appConstants } from './app.constant';

const item: string = 'item';

export const itemConstants: ItemConstants = {
  REQUEST_GET_DEPARTMENT_ITEMS: 'REQUEST_GET_DEPARTMENT_ITEMS',
  GET_DEPARTMENT_ITEMS_SUCCESS: 'GET_DEPARTMENT_ITEMS_SUCCESS',
  GET_DEPARTMENT_ITEMS_ERROR: 'GET_DEPARTMENT_ITEMS_ERROR',

  REQUEST_GET_ALL_DEPARTMENT_ITEMS: 'REQUEST_GET_ALL_DEPARTMENT_ITEMS',
  GET_ALL_DEPARTMENT_ITEMS_SUCCESS: 'GET_ALL_DEPARTMENT_ITEMS_SUCCESS',
  GET_ALL_DEPARTMENT_ITEMS_ERROR: 'GET_ALL_DEPARTMENT_ITEMS_ERROR',

  REQUEST_GET_ALL_ITEMS: 'REQUEST_GET_ALL_ITEMS',
  GET_ALL_ITEMS_SUCCESS: 'GET_ALL_ITEMS_SUCCESS',
  GET_ALL_ITEMS_ERROR: 'GET_ALL_ITEMS_ERROR',

  REQUEST_GET_AN_ITEM: 'REQUEST_GET_AN_ITEM',
  GET_AN_ITEM_SUCCESS: 'GET_AN_ITEM_SUCCESS',
  GET_AN_ITEM_ERROR: 'GET_AN_ITEM_ERROR',

  REQUEST_CREATE_ITEM: 'REQUEST_CREATE_ITEM',
  CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
  CREATE_ITEMS_SUCCESS: 'CREATE_ITEMS_SUCCESS',
  CREATE_ITEM_ERROR: 'CREATE_ITEM_ERROR',

  REQUEST_UPDATE_ITEM: 'REQUEST_UPDATE_ITEM',
  UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_ERROR: 'UPDATE_ITEM_ERROR',

  REQUEST_DELETE_ITEM: 'REQUEST_DELETE_ITEM',
  DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
  DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',

  REQUEST_SEARCH_ITEM: 'REQUEST_SEARCH_ITEM',
  SEARCH_ITEM_SUCCESS: 'SEARCH_ITEM_SUCCESS',
  SEARCH_ITEM_ERROR: 'SEARCH_ITEM_ERROR',

  GET_DEPARTMENT_ITEMS: 'GET_DEPARTMENT_ITEMS',
  GET_ALL_DEPARTMENT_ITEMS: 'GET_ALL_DEPARTMENT_ITEMS',
  GET_ALL_ITEMS: 'GET_ALL_ITEMS',

  GET_AN_ITEM: 'GET_AN_ITEM',
  CREATE_ITEM: 'CREATE_ITEM',
  CREATE_ITEMS: 'CREATE_ITEMS',

  UPDATE_ITEM: 'UPDATE_ITEM',
  UPDATE_ITEM_BASIC: 'UPDATE_ITEM_BASIC',
  REQUEST_UPDATE_ITEM_BASIC: 'REQUEST_UPDATE_ITEM_BASIC',
  UPDATE_ITEM_BASIC_SUCCESS: 'UPDATE_ITEM_BASIC_SUCCESS',
  UPDATE_ITEM_BASIC_ERROR: 'UPDATE_ITEM_BASIC_ERROR',
  SEARCH_ITEM: 'SEARCH_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',

  ITEM_URI: `${appConstants.BASE_URI}${item}`,
};
