import { MaintenanceConstants } from '@/types';
import { appConstants } from './app.constant';

const maintenance: string = 'maintenance-log';

export const maintenanceConstants: MaintenanceConstants = {
  REQUEST_GET_MAINTENANCE_LOGS: 'REQUEST_GET_MAINTENANCE_LOGS',
  GET_MAINTENANCE_LOGS_SUCCESS: 'GET_MAINTENANCE_LOGS_SUCCESS',
  GET_MAINTENANCE_LOGS_ERROR: 'GET_MAINTENANCE_LOGS_ERROR',

  REQUEST_SEARCH_MAINTENANCE_LOG: 'REQUEST_SEARCH_MAINTENANCE_LOG',
  SEARCH_MAINTENANCE_LOG_SUCCESS: 'SEARCH_MAINTENANCE_LOG_SUCCESS',
  SEARCH_MAINTENANCE_LOG_ERROR: 'SEARCH_MAINTENANCE_LOG_ERROR',

  GET_MAINTENANCE_LOGS: 'GET_MAINTENANCE_LOGS',
  SEARCH_MAINTENANCE_LOG: 'SEARCH_MAINTENANCE_LOG',

  MAINTENANCE_URI: `${appConstants.BASE_URI}${maintenance}`,
};
