import { appConstants } from './app.constant';

const maintenanceSchedule: string = 'maintenance-schedule';

export const maintenanceScheduleConstants = {
  GET_ALL_MAINTENANCE_SCHEDULES: 'GET_ALL_MAINTENANCE_SCHEDULES',
  REQUEST_GET_ALL_MAINTENANCE_SCHEDULES: 'REQUEST_GET_ALL_MAINTENANCE_SCHEDULES',
  GET_ALL_MAINTENANCE_SCHEDULES_SUCCESS: 'GET_ALL_MAINTENANCE_SCHEDULES_SUCCESS',
  GET_ALL_MAINTENANCE_SCHEDULES_ERROR: 'GET_ALL_MAINTENANCE_SCHEDULES_ERROR',

  CREATE_MAINTENANCE_SCHEDULE: 'CREATE_MAINTENANCE_SCHEDULE',
  REQUEST_CREATE_MAINTENANCE_SCHEDULE: 'REQUEST_CREATE_MAINTENANCE_SCHEDULE',
  CREATE_MAINTENANCE_SCHEDULE_SUCCESS: 'CREATE_MAINTENANCE_SCHEDULE_SUCCESS',
  CREATE_MAINTENANCE_SCHEDULE_ERROR: 'CREATE_MAINTENANCE_SCHEDULE_ERROR',

  UPDATE_MAINTENANCE_SCHEDULE: 'UPDATE_MAINTENANCE_SCHEDULE',
  REQUEST_UPDATE_MAINTENANCE_SCHEDULE: 'REQUEST_UPDATE_MAINTENANCE_SCHEDULE',
  UPDATE_MAINTENANCE_SCHEDULE_SUCCESS: 'UPDATE_MAINTENANCE_SCHEDULE_SUCCESS',
  UPDATE_MAINTENANCE_SCHEDULE_ERROR: 'UPDATE_MAINTENANCE_SCHEDULE_ERROR',

  MAINTENANCE_SCHEDULE_URI: `${appConstants.BASE_URI}${maintenanceSchedule}`,
};
