import { appConstants } from './app.constant';

const meeting: string = 'meetings';

export const meetingConstants = {
  MEETING_URI: `${appConstants.BASE_URI}${meeting}`,

  GET_MEETINGS: 'GET_MEETINGS',
  REQUEST_GET_MEETINGS: 'REQUEST_GET_MEETINGS',
  GET_MEETINGS_SUCCESS: 'GET_MEETINGS_SUCCESS',
  GET_MEETINGS_FAILURE: 'GET_MEETINGS_FAILURE',

  CREATE_MEETING: 'CREATE_MEETING',
  REQUEST_CREATE_MEETING: 'REQUEST_CREATE_MEETING',
  CREATE_MEETING_SUCCESS: 'CREATE_MEETING_SUCCESS',
  CREATE_MEETING_FAILURE: 'CREATE_MEETING_FAILURE',

  UPDATE_MEETING: 'UPDATE_MEETING',
  REQUEST_UPDATE_MEETING: 'REQUEST_UPDATE_MEETING',
  UPDATE_MEETING_SUCCESS: 'UPDATE_MEETING_SUCCESS',
  UPDATE_MEETING_FAILURE: 'UPDATE_MEETING_FAILURE',

  DELETE_MEETING: 'DELETE_MEETING',
  REQUEST_DELETE_MEETING: 'REQUEST_DELETE_MEETING',
  DELETE_MEETING_SUCCESS: 'DELETE_MEETING_SUCCESS',
  DELETE_MEETING_FAILURE: 'DELETE_MEETING_FAILURE',
};
