import { appConstants } from './app.constant';

const meetingLocation: string = 'meeting-locations';

export const meetingLocationConstants = {
  MEETING_LOCATION_URI: `${appConstants.BASE_URI}${meetingLocation}`,

  GET_MEETING_LOCATIONS: 'GET_MEETING_LOCATIONS',
  REQUEST_GET_MEETING_LOCATIONS: 'REQUEST_GET_MEETING_LOCATIONS',
  GET_MEETING_LOCATIONS_SUCCESS: 'GET_MEETING_LOCATIONS_SUCCESS',
  GET_MEETING_LOCATIONS_FAILURE: 'GET_MEETING_LOCATIONS_FAILURE',

  CREATE_MEETING_LOCATION: 'CREATE_MEETING_LOCATION',
  REQUEST_CREATE_MEETING_LOCATION: 'REQUEST_CREATE_MEETING_LOCATION',
  CREATE_MEETING_LOCATION_SUCCESS: 'CREATE_MEETING_LOCATION_SUCCESS',
  CREATE_MEETING_LOCATION_FAILURE: 'CREATE_MEETING_LOCATION_FAILURE',

  UPDATE_MEETING_LOCATION: 'UPDATE_MEETING_LOCATION',
  REQUEST_UPDATE_MEETING_LOCATION: 'REQUEST_UPDATE_MEETING_LOCATION',
  UPDATE_MEETING_LOCATION_SUCCESS: 'UPDATE_MEETING_LOCATION_SUCCESS',
  UPDATE_MEETING_LOCATION_FAILURE: 'UPDATE_MEETING_LOCATION_FAILURE',

  DELETE_MEETING_LOCATION: 'DELETE_MEETING_LOCATION',
  REQUEST_DELETE_MEETING_LOCATION: 'REQUEST_DELETE_MEETING_LOCATION',
  DELETE_MEETING_LOCATION_SUCCESS: 'DELETE_MEETING_LOCATION_SUCCESS',
  DELETE_MEETING_LOCATION_FAILURE: 'DELETE_MEETING_LOCATION_FAILURE',
};
