import { appConstants } from '@/constants/app.constant';

// No leading slash — BASE_URI already ends with one.
const notification = 'notification';

export const notificationConstants = {
   // API URIs — prepend BASE_URI so callers don't end up hitting the
   // Next.js dev server when they pass these straight to fetch().
   NOTIFICATION_URI: `${appConstants.BASE_URI}${notification}`,
   NOTIFICATION_SUMMARY_URI: `${appConstants.BASE_URI}${notification}/summary`,
   NOTIFICATION_READ_URI: `${appConstants.BASE_URI}${notification}/{id}/read`,
   NOTIFICATION_READ_ALL_URI: `${appConstants.BASE_URI}${notification}/read-all`,
   NOTIFICATION_STREAM_TICKET_URI: `${appConstants.BASE_URI}${notification}/stream/ticket`,
   NOTIFICATION_STREAM_URI: `${appConstants.BASE_URI}${notification}/stream`,

   // Action types
   GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
   REQUEST_GET_NOTIFICATIONS: 'REQUEST_GET_NOTIFICATIONS',
   GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
   GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',

   GET_NOTIFICATION_SUMMARY: 'GET_NOTIFICATION_SUMMARY',
   GET_NOTIFICATION_SUMMARY_SUCCESS: 'GET_NOTIFICATION_SUMMARY_SUCCESS',

   MARK_NOTIFICATION_READ: 'MARK_NOTIFICATION_READ',
   MARK_NOTIFICATION_READ_SUCCESS: 'MARK_NOTIFICATION_READ_SUCCESS',
   MARK_NOTIFICATION_READ_ERROR: 'MARK_NOTIFICATION_READ_ERROR',

   MARK_ALL_NOTIFICATIONS_READ: 'MARK_ALL_NOTIFICATIONS_READ',
   MARK_ALL_NOTIFICATIONS_READ_SUCCESS: 'MARK_ALL_NOTIFICATIONS_READ_SUCCESS',
   MARK_ALL_NOTIFICATIONS_READ_ERROR: 'MARK_ALL_NOTIFICATIONS_READ_ERROR',

   // SSE
   CONNECT_NOTIFICATION_STREAM: 'CONNECT_NOTIFICATION_STREAM',
   DISCONNECT_NOTIFICATION_STREAM: 'DISCONNECT_NOTIFICATION_STREAM',
   NOTIFICATION_STREAM_OPENED: 'NOTIFICATION_STREAM_OPENED',
   NOTIFICATION_STREAM_CLOSED: 'NOTIFICATION_STREAM_CLOSED',
   NOTIFICATION_RECEIVED: 'NOTIFICATION_RECEIVED',
} as const;
