export const notificationConstants = {
   // API URIs
   NOTIFICATION_URI: '/notification',
   NOTIFICATION_SUMMARY_URI: '/notification/summary',
   NOTIFICATION_READ_URI: '/notification/{id}/read',
   NOTIFICATION_READ_ALL_URI: '/notification/read-all',
   NOTIFICATION_STREAM_TICKET_URI: '/notification/stream/ticket',
   NOTIFICATION_STREAM_URI: '/notification/stream',

   // Action types
   GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
   REQUEST_GET_NOTIFICATIONS: 'REQUEST_GET_NOTIFICATIONS',
   GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
   GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',

   GET_NOTIFICATION_SUMMARY: 'GET_NOTIFICATION_SUMMARY',
   GET_NOTIFICATION_SUMMARY_SUCCESS: 'GET_NOTIFICATION_SUMMARY_SUCCESS',

   MARK_NOTIFICATION_READ: 'MARK_NOTIFICATION_READ',
   MARK_NOTIFICATION_READ_SUCCESS: 'MARK_NOTIFICATION_READ_SUCCESS',
   MARK_NOTIFICATION_READ_ERROR: 'MARK_NOTIFICATION_READ_ERROR',

   MARK_ALL_NOTIFICATIONS_READ: 'MARK_ALL_NOTIFICATIONS_READ',
   MARK_ALL_NOTIFICATIONS_READ_SUCCESS: 'MARK_ALL_NOTIFICATIONS_READ_SUCCESS',
   MARK_ALL_NOTIFICATIONS_READ_ERROR: 'MARK_ALL_NOTIFICATIONS_READ_ERROR',

   // SSE
   CONNECT_NOTIFICATION_STREAM: 'CONNECT_NOTIFICATION_STREAM',
   DISCONNECT_NOTIFICATION_STREAM: 'DISCONNECT_NOTIFICATION_STREAM',
   NOTIFICATION_STREAM_OPENED: 'NOTIFICATION_STREAM_OPENED',
   NOTIFICATION_STREAM_CLOSED: 'NOTIFICATION_STREAM_CLOSED',
   NOTIFICATION_RECEIVED: 'NOTIFICATION_RECEIVED',
} as const;
