import { appConstants } from './app.constant';

const permission: string = 'permission';

export const permissionConstants = {
   PERMISSION_URI: `${appConstants.BASE_URI}${permission}`,
   PERMISSION_ALL_URI: `${appConstants.BASE_URI}${permission}/all`,

   GET_PERMISSIONS: 'GET_PERMISSIONS',
   REQUEST_GET_PERMISSIONS: 'REQUEST_GET_PERMISSIONS',
   GET_PERMISSIONS_SUCCESS: 'GET_PERMISSIONS_SUCCESS',
   GET_PERMISSIONS_FAILURE: 'GET_PERMISSIONS_FAILURE',

   CREATE_PERMISSION: 'CREATE_PERMISSION',
   REQUEST_CREATE_PERMISSION: 'REQUEST_CREATE_PERMISSION',
   CREATE_PERMISSION_SUCCESS: 'CREATE_PERMISSION_SUCCESS',
   CREATE_PERMISSION_FAILURE: 'CREATE_PERMISSION_FAILURE',

   UPDATE_PERMISSION: 'UPDATE_PERMISSION',
   REQUEST_UPDATE_PERMISSION: 'REQUEST_UPDATE_PERMISSION',
   UPDATE_PERMISSION_SUCCESS: 'UPDATE_PERMISSION_SUCCESS',
   UPDATE_PERMISSION_FAILURE: 'UPDATE_PERMISSION_FAILURE',

   DELETE_PERMISSION: 'DELETE_PERMISSION',
   REQUEST_DELETE_PERMISSION: 'REQUEST_DELETE_PERMISSION',
   DELETE_PERMISSION_SUCCESS: 'DELETE_PERMISSION_SUCCESS',
   DELETE_PERMISSION_FAILURE: 'DELETE_PERMISSION_FAILURE',
};
