import { ReconciliationConstants } from '@/types';
import { appConstants } from './app.constant';

export const reconciliationConstants: ReconciliationConstants = {
  GET_RECONCILIATIONS: 'GET_RECONCILIATIONS',
  REQUEST_GET_RECONCILIATIONS: 'REQUEST_GET_RECONCILIATIONS',
  GET_RECONCILIATIONS_SUCCESS: 'GET_RECONCILIATIONS_SUCCESS',
  GET_RECONCILIATIONS_ERROR: 'GET_RECONCILIATIONS_ERROR',

  OPEN_RECONCILIATION: 'OPEN_RECONCILIATION',
  REQUEST_OPEN_RECONCILIATION: 'REQUEST_OPEN_RECONCILIATION',
  OPEN_RECONCILIATION_SUCCESS: 'OPEN_RECONCILIATION_SUCCESS',
  OPEN_RECONCILIATION_ERROR: 'OPEN_RECONCILIATION_ERROR',

  GET_RECONCILIATION_DETAIL: 'GET_RECONCILIATION_DETAIL',
  REQUEST_GET_RECONCILIATION_DETAIL: 'REQUEST_GET_RECONCILIATION_DETAIL',
  GET_RECONCILIATION_DETAIL_SUCCESS: 'GET_RECONCILIATION_DETAIL_SUCCESS',
  GET_RECONCILIATION_DETAIL_ERROR: 'GET_RECONCILIATION_DETAIL_ERROR',

  SAVE_COUNTS: 'SAVE_COUNTS',
  REQUEST_SAVE_COUNTS: 'REQUEST_SAVE_COUNTS',
  SAVE_COUNTS_SUCCESS: 'SAVE_COUNTS_SUCCESS',
  SAVE_COUNTS_ERROR: 'SAVE_COUNTS_ERROR',

  SUBMIT_RECONCILIATION: 'SUBMIT_RECONCILIATION',
  REQUEST_SUBMIT_RECONCILIATION: 'REQUEST_SUBMIT_RECONCILIATION',
  SUBMIT_RECONCILIATION_SUCCESS: 'SUBMIT_RECONCILIATION_SUCCESS',
  SUBMIT_RECONCILIATION_ERROR: 'SUBMIT_RECONCILIATION_ERROR',

  APPROVE_RECONCILIATION: 'APPROVE_RECONCILIATION',
  REQUEST_APPROVE_RECONCILIATION: 'REQUEST_APPROVE_RECONCILIATION',
  APPROVE_RECONCILIATION_SUCCESS: 'APPROVE_RECONCILIATION_SUCCESS',
  APPROVE_RECONCILIATION_ERROR: 'APPROVE_RECONCILIATION_ERROR',

  REJECT_RECONCILIATION: 'REJECT_RECONCILIATION',
  REQUEST_REJECT_RECONCILIATION: 'REQUEST_REJECT_RECONCILIATION',
  REJECT_RECONCILIATION_SUCCESS: 'REJECT_RECONCILIATION_SUCCESS',
  REJECT_RECONCILIATION_ERROR: 'REJECT_RECONCILIATION_ERROR',

  GET_RECONCILIATION_REPORT: 'GET_RECONCILIATION_REPORT',
  REQUEST_GET_RECONCILIATION_REPORT: 'REQUEST_GET_RECONCILIATION_REPORT',
  GET_RECONCILIATION_REPORT_SUCCESS: 'GET_RECONCILIATION_REPORT_SUCCESS',
  GET_RECONCILIATION_REPORT_ERROR: 'GET_RECONCILIATION_REPORT_ERROR',

  RECONCILIATION_URI: `${appConstants.BASE_URI}reconciliation`,
};
