import { ReportConstants } from '@/types';
import { appConstants } from './app.constant';

const report: string = 'complaint';

export const reportConstants: ReportConstants = {
  REQUEST_SEND_REPORT: 'REQUEST_SEND_REPORT',
  SEND_REPORT_SUCCESS: 'SEND_REPORT_SUCCESS',
  SEND_REPORT_ERROR: 'SEND_REPORT_ERROR',

  REQUEST_GET_REPORTS: 'REQUEST_GET_REPORTS',
  GET_REPORTS_SUCCESS: 'GET_REPORTS_SUCCESS',
  GET_REPORTS_ERROR: 'GET_REPORTS_ERROR',

  REQUEST_SEARCH_REPORT: 'REQUEST_SEARCH_REPORT',
  SEARCH_REPORT_SUCCESS: 'SEARCH_REPORT_SUCCESS',
  SEARCH_REPORT_ERROR: 'SEARCH_REPORT_ERROR',

  UPDATE_REPORT_SUCCESS: 'UPDATE_REPORT_SUCCESS',

  SEND_REPORT: 'SEND_REPORT',
  GET_REPORTS: 'GET_REPORTS',
  SEARCH_REPORT: 'SEARCH_REPORT',

  // Workflow Rules Module (Phase 4) — fetch the engine's verdict on
  // which complaint actions the current viewer can fire. Mirrors the
  // requestConstants.GET_REQUEST_ACTIONS shape so the page wiring
  // and reducer pattern are identical.
  GET_REPORT_ACTIONS: 'GET_REPORT_ACTIONS',
  REQUEST_GET_REPORT_ACTIONS: 'REQUEST_GET_REPORT_ACTIONS',
  GET_REPORT_ACTIONS_SUCCESS: 'GET_REPORT_ACTIONS_SUCCESS',
  GET_REPORT_ACTIONS_FAILURE: 'GET_REPORT_ACTIONS_FAILURE',
  RESET_REPORT_ACTIONS: 'RESET_REPORT_ACTIONS',

  REPORT_URI: `${appConstants.BASE_URI}${report}`,
};
