import { RequestConstants } from '@/types';
import { appConstants } from './app.constant';

const request: string = 'request';

export const requestConstants: RequestConstants = {
  REQUEST_CREATE_REQUEST: 'REQUEST_CREATE_REQUEST',
  CREATE_REQUEST_SUCCESS: 'CREATE_REQUEST_SUCCESS',
  CREATE_REQUEST_ERROR: 'CREATE_REQUEST_ERROR',

  REQUEST_GET_ALL_REQUESTS: 'REQUEST_GET_ALL_REQUESTS',
  GET_ALL_REQUESTS_SUCCESS: 'GET_ALL_REQUESTS_SUCCESS',
  GET_ALL_REQUESTS_ERROR: 'GET_ALL_REQUESTS_ERROR',

  REQUEST_GET_DEPARTMENT_REQUESTS: 'REQUEST_GET_DEPARTMENT_REQUESTS',
  GET_DEPARTMENT_REQUESTS_SUCCESS: 'GET_DEPARTMENT_REQUESTS_SUCCESS',
  GET_DEPARTMENT_REQUESTS_ERROR: 'GET_DEPARTMENT_REQUESTS_ERROR',

  REQUEST_GET_ASSIGNED_REQUESTS: 'REQUEST_GET_ASSIGNED_REQUESTS',
  GET_ASSIGNED_REQUESTS_SUCCESS: 'GET_ASSIGNED_REQUESTS_SUCCESS',
  GET_ASSIGNED_REQUESTS_ERROR: 'GET_ASSIGNED_REQUESTS_ERROR',

  REQUEST_UPDATE_REQUEST_STATUS: 'REQUEST_UPDATE_REQUEST_STATUS',
  UPDATE_REQUEST_STATUS_SUCCESS: 'UPDATE_REQUEST_STATUS_SUCCESS',
  UPDATE_REQUEST_STATUS_ERROR: 'UPDATE_REQUEST_STATUS_ERROR',

  REQUEST_ASSIGN_REQUEST: 'REQUEST_ASSIGN_REQUEST',
  ASSIGN_REQUEST_SUCCESS: 'ASSIGN_REQUEST_SUCCESS',
  ASSIGN_REQUEST_ERROR: 'ASSIGN_REQUEST_ERROR',

  REQUEST_RELEASE_REQUEST_ITEMS: 'REQUEST_RELEASE_REQUEST_ITEMS',
  RELEASE_REQUEST_ITEMS_SUCCESS: 'RELEASE_REQUEST_ITEMS_SUCCESS',
  RELEASE_REQUEST_ITEMS_ERROR: 'RELEASE_REQUEST_ITEMS_ERROR',

  REQUEST_RETURN_REQUEST_ITEMS: 'REQUEST_RETURN_REQUEST_ITEMS',
  RETURN_REQUEST_ITEMS_SUCCESS: 'RETURN_REQUEST_ITEMS_SUCCESS',
  RETURN_REQUEST_ITEMS_ERROR: 'RETURN_REQUEST_ITEMS_ERROR',

  // Workflow Rules Module (Phase 3) — server-driven action gates.
  GET_REQUEST_ACTIONS: 'GET_REQUEST_ACTIONS',
  REQUEST_GET_REQUEST_ACTIONS: 'REQUEST_GET_REQUEST_ACTIONS',
  GET_REQUEST_ACTIONS_SUCCESS: 'GET_REQUEST_ACTIONS_SUCCESS',
  GET_REQUEST_ACTIONS_FAILURE: 'GET_REQUEST_ACTIONS_FAILURE',
  RESET_REQUEST_ACTIONS: 'RESET_REQUEST_ACTIONS',

  CREATE_REQUEST: 'CREATE_REQUEST',
  GET_ALL_REQUESTS: 'GET_ALL_REQUESTS',
  GET_DEPARTMENT_REQUESTS: 'GET_DEPARTMENT_REQUESTS',
  GET_ASSIGNED_REQUESTS: 'GET_ASSIGNED_REQUESTS',

  UPDATE_REQUEST_STATUS: 'UPDATE_REQUEST_STATUS',
  ASSIGN_REQUEST: 'ASSIGN_REQUEST',
  RELEASE_REQUEST_ITEMS: 'RELEASE_REQUEST_ITEMS',
  RETURN_REQUEST_ITEMS: 'RETURN_REQUEST_ITEMS',

  REQUEST_URI: `${appConstants.BASE_URI}${request}`,
  VERIFY_REQUEST_TOKEN_URI: `${appConstants.BASE_URI}${request}/verify-token`,
};

// v2 multi-department submission endpoint. v1 (`/request/new`) is left
// in place for backward compat; the redesigned form always POSTs JSON
// to /v2 with a per-row `{ departmentId, itemId, quantity }[]` items
// array — see Multi-Department Requests Spec §7.3 / §11 Phase 5.
export const CREATE_REQUEST_V2_URI = `${appConstants.BASE_URI}${request}/new/v2`;
