import { RequestConstants } from '@/types';
import { appConstants } from './app.constant';

const request: string = 'request';

export const requestConstants: RequestConstants = {
  REQUEST_CREATE_REQUEST: 'REQUEST_CREATE_REQUEST',
  CREATE_REQUEST_SUCCESS: 'CREATE_REQUEST_SUCCESS',
  CREATE_REQUEST_ERROR: 'CREATE_REQUEST_ERROR',

  REQUEST_GET_ALL_REQUESTS: 'REQUEST_GET_ALL_REQUESTS',
  GET_ALL_REQUESTS_SUCCESS: 'GET_ALL_REQUESTS_SUCCESS',
  GET_ALL_REQUESTS_ERROR: 'GET_ALL_REQUESTS_ERROR',

  REQUEST_GET_DEPARTMENT_REQUESTS: 'REQUEST_GET_DEPARTMENT_REQUESTS',
  GET_DEPARTMENT_REQUESTS_SUCCESS: 'GET_DEPARTMENT_REQUESTS_SUCCESS',
  GET_DEPARTMENT_REQUESTS_ERROR: 'GET_DEPARTMENT_REQUESTS_ERROR',

  REQUEST_UPDATE_REQUEST_STATUS: 'REQUEST_UPDATE_REQUEST_STATUS',
  UPDATE_REQUEST_STATUS_SUCCESS: 'UPDATE_REQUEST_STATUS_SUCCESS',
  UPDATE_REQUEST_STATUS_ERROR: 'UPDATE_REQUEST_STATUS_ERROR',

  CREATE_REQUEST: 'CREATE_REQUEST',
  GET_ALL_REQUESTS: 'GET_ALL_REQUESTS',
  GET_DEPARTMENT_REQUESTS: 'GET_DEPARTMENT_REQUESTS',
  UPDATE_REQUEST_STATUS: 'UPDATE_REQUEST_STATUS',

  REQUEST_URI: `${appConstants.BASE_URI}${request}`,
};
