import { appConstants } from './app.constant';

export const roleConstants = {
   ROLE_URI: `${appConstants.BASE_URI}role`,
   ROLE_ALL_URI: `${appConstants.BASE_URI}role/all`,

   GET_ROLES: 'GET_ROLES',
   REQUEST_GET_ROLES: 'REQUEST_GET_ROLES',
   GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
   GET_ROLES_FAILURE: 'GET_ROLES_FAILURE',

   GET_ROLE: 'GET_ROLE',
   REQUEST_GET_ROLE: 'REQUEST_GET_ROLE',
   GET_ROLE_SUCCESS: 'GET_ROLE_SUCCESS',
   GET_ROLE_FAILURE: 'GET_ROLE_FAILURE',

   CREATE_ROLE: 'CREATE_ROLE',
   REQUEST_CREATE_ROLE: 'REQUEST_CREATE_ROLE',
   CREATE_ROLE_SUCCESS: 'CREATE_ROLE_SUCCESS',
   CREATE_ROLE_FAILURE: 'CREATE_ROLE_FAILURE',

   UPDATE_ROLE: 'UPDATE_ROLE',
   REQUEST_UPDATE_ROLE: 'REQUEST_UPDATE_ROLE',
   UPDATE_ROLE_SUCCESS: 'UPDATE_ROLE_SUCCESS',
   UPDATE_ROLE_FAILURE: 'UPDATE_ROLE_FAILURE',

   DELETE_ROLE: 'DELETE_ROLE',
   REQUEST_DELETE_ROLE: 'REQUEST_DELETE_ROLE',
   DELETE_ROLE_SUCCESS: 'DELETE_ROLE_SUCCESS',
   DELETE_ROLE_FAILURE: 'DELETE_ROLE_FAILURE',

   GET_AVAILABLE_PERMISSIONS: 'GET_AVAILABLE_PERMISSIONS',
   REQUEST_GET_AVAILABLE_PERMISSIONS: 'REQUEST_GET_AVAILABLE_PERMISSIONS',
   GET_AVAILABLE_PERMISSIONS_SUCCESS: 'GET_AVAILABLE_PERMISSIONS_SUCCESS',
   GET_AVAILABLE_PERMISSIONS_FAILURE: 'GET_AVAILABLE_PERMISSIONS_FAILURE',

   GET_ASSIGNED_PERMISSIONS: 'GET_ASSIGNED_PERMISSIONS',
   REQUEST_GET_ASSIGNED_PERMISSIONS: 'REQUEST_GET_ASSIGNED_PERMISSIONS',
   GET_ASSIGNED_PERMISSIONS_SUCCESS: 'GET_ASSIGNED_PERMISSIONS_SUCCESS',
   GET_ASSIGNED_PERMISSIONS_FAILURE: 'GET_ASSIGNED_PERMISSIONS_FAILURE',

   ADD_PERMISSIONS_TO_ROLE: 'ADD_PERMISSIONS_TO_ROLE',
   REQUEST_ADD_PERMISSIONS_TO_ROLE: 'REQUEST_ADD_PERMISSIONS_TO_ROLE',
   ADD_PERMISSIONS_TO_ROLE_SUCCESS: 'ADD_PERMISSIONS_TO_ROLE_SUCCESS',
   ADD_PERMISSIONS_TO_ROLE_FAILURE: 'ADD_PERMISSIONS_TO_ROLE_FAILURE',

   REMOVE_PERMISSIONS_FROM_ROLE: 'REMOVE_PERMISSIONS_FROM_ROLE',
   REQUEST_REMOVE_PERMISSIONS_FROM_ROLE: 'REQUEST_REMOVE_PERMISSIONS_FROM_ROLE',
   REMOVE_PERMISSIONS_FROM_ROLE_SUCCESS: 'REMOVE_PERMISSIONS_FROM_ROLE_SUCCESS',
   REMOVE_PERMISSIONS_FROM_ROLE_FAILURE: 'REMOVE_PERMISSIONS_FROM_ROLE_FAILURE',

   REPLACE_ROLE_PERMISSIONS: 'REPLACE_ROLE_PERMISSIONS',
   REPLACE_ROLE_PERMISSIONS_SUCCESS: 'REPLACE_ROLE_PERMISSIONS_SUCCESS',
   REPLACE_ROLE_PERMISSIONS_ERROR: 'REPLACE_ROLE_PERMISSIONS_ERROR',
};
