import { appConstants } from './app.constant';

const base = `${appConstants.BASE_URI}authentication`;

export const securityConstants = {
   GET_SESSIONS: 'GET_SESSIONS',
   REQUEST_GET_SESSIONS: 'REQUEST_GET_SESSIONS',
   GET_SESSIONS_SUCCESS: 'GET_SESSIONS_SUCCESS',
   GET_SESSIONS_FAILURE: 'GET_SESSIONS_FAILURE',

   REVOKE_SESSION: 'REVOKE_SESSION',
   REQUEST_REVOKE_SESSION: 'REQUEST_REVOKE_SESSION',
   REVOKE_SESSION_SUCCESS: 'REVOKE_SESSION_SUCCESS',
   REVOKE_SESSION_FAILURE: 'REVOKE_SESSION_FAILURE',

   REVOKE_ALL_SESSIONS: 'REVOKE_ALL_SESSIONS',
   REQUEST_REVOKE_ALL_SESSIONS: 'REQUEST_REVOKE_ALL_SESSIONS',
   REVOKE_ALL_SESSIONS_SUCCESS: 'REVOKE_ALL_SESSIONS_SUCCESS',
   REVOKE_ALL_SESSIONS_FAILURE: 'REVOKE_ALL_SESSIONS_FAILURE',

   GET_LOGIN_HISTORY: 'GET_LOGIN_HISTORY',
   REQUEST_GET_LOGIN_HISTORY: 'REQUEST_GET_LOGIN_HISTORY',
   GET_LOGIN_HISTORY_SUCCESS: 'GET_LOGIN_HISTORY_SUCCESS',
   GET_LOGIN_HISTORY_FAILURE: 'GET_LOGIN_HISTORY_FAILURE',

   SESSIONS_URI: `${base}/sessions`,
   LOGIN_HISTORY_URI: `${base}/login-history`,
};
