import {
  DashboardIcon,
  DepartmentsIcon,
  GeneratorLogIcon,
  ItemsIcon,
  MaintenanceLog,
  ReportsIcon,
  RequestsIcon,
  StoreIcon,
  // UsersIcon,
} from '@/components/Icons';

export const pageRoutes = [
  {
    id: 1,
    label: 'dashboard',
    link: '/admin/dashboard',
    icon: <DashboardIcon />,
    allowedRoles: [5, 1, 2, 3, 4],
  },
  {
    id: 2,
    label: 'requests',
    link: '/admin/requests',
    icon: <RequestsIcon />,
    allowedRoles: [5, 1, 3, 4],
  },
  {
    id: 3,
    label: 'items',
    link: '/admin/items',
    icon: <ItemsIcon />,
    allowedRoles: [5, 1, 2, 3, 4],
  },
  {
    id: 4,
    label: 'store',
    link: '/admin/store',
    icon: <StoreIcon />,
    allowedRoles: [5, 1],
  },
  {
    id: 5,
    label: 'departments',
    link: '/admin/departments',
    icon: <DepartmentsIcon />,
    allowedRoles: [5, 1],
  },
  {
    id: 6,
    label: 'maintenance log',
    link: '/admin/maintenance-log',
    icon: <MaintenanceLog />,
    allowedRoles: [5, 1, 4],
  },
  {
    id: 7,
    label: 'generator log',
    link: '/admin/generator-log',
    icon: <GeneratorLogIcon />,
    allowedRoles: [5, 1, 4],
  },
  {
    id: 8,
    label: 'reports',
    link: '/admin/reports',
    icon: <ReportsIcon />,
    allowedRoles: [5, 1, 4],
  },
  {
    id: 8,
    label: 'users',
    link: '/admin/users',
    icon: <ReportsIcon />,
    allowedRoles: [5, 1],
  },
];
